Minor changes to fix issues compiling with clang
Error:
  xUSL/CCX/Common/CcxMiscInit.c:78:17:
  error: variable 'tempWa' set but not used
Solution:
  Get rid of tempWa variable, cast variables to void to mark them as
  used.

Error:
  xUSL/CCX/Zen4/CcxCmn2Zen4.c:153:84:
  error: for loop has empty body
Solution:
  Move semicolon to a separate line to silence the warning.

Error:
  xUSL/Mpio/Common/MpioTopology.c:105:30:
  error: variable 'Index' set but not used
Solution:
  Remove Index variable which is indeed unused.

Signed-off-by: Martin Roth <gaumless@gmail.com>
Change-Id: Ib999551942188bfe8a131ac97e10c964c679a66e
Reviewed-on: https://review.coreboot.org/c/opensil_genoa_poc/+/78918
Reviewed-by: Matt DeVillier <matt.devillier@amd.corp-partner.google.com>